# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-10 09:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0002_typeofwork'),
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worksheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importdatetime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('comment', models.TextField(blank=True)),
                ('original', models.FileField(upload_to='uploads')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.Partner')),
                ('typeOfWork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branches.TypeOfWork')),
            ],
        ),
    ]
