# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-10 14:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worksheets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorksheetFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.FileField(upload_to='uploads')),
                ('fileName', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='worksheet',
            name='original',
        ),
        migrations.AddField(
            model_name='worksheet',
            name='originalFile',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='worksheets.WorksheetFile'),
        ),
    ]
